import { useState, useEffect } from 'react';
import { GraduationCap, Trophy, ArrowLeft, ShieldCheck, CheckCircle2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { lessons } from '@/lib/cyber/lessons';
import { supabase } from '@/integrations/supabase/client';
import { useSession } from './session';
import { Link } from '@tanstack/react-router';
export function AcademyPage(){const {user}=useSession();const [active,setActive]=useState<typeof lessons[number]|null>(null);const [answer,setAnswer]=useState<number|null>(null);const [completed,setCompleted]=useState<string[]>([]);const [status,setStatus]=useState('');const [busy,setBusy]=useState(false);useEffect(()=>{setCompleted([]);if(user)supabase.from('lesson_rewards').select('lesson').then(({data,error})=>{if(error)setStatus('Progress is unavailable.');else setCompleted((data??[]).map(r=>r.lesson));});},[user]);async function choose(i:number){setAnswer(i);setStatus('');if(!active||i!==active.answer)return;if(!user){setStatus('Correct. Sign in to earn and save virtual CyberCoins.');return;}setBusy(true);const {data,error}=await supabase.rpc('complete_safety_lesson',{p_lesson:active.id,p_answer:i});if(error)setStatus('Your answer was correct, but progress could not be saved. Retry later.');else if(data){setStatus(completed.includes(active.id)?'Already completed. No duplicate points awarded.':'Lesson verified. You earned 25 virtual CyberCoins.');setCompleted([...new Set([...completed,active.id])]);}setBusy(false);}return <div className="page"><div className="page-heading"><div><p className="eyebrow">CYBER SAFETY ACADEMY</p><h1>Build a stronger cyber instinct.</h1><p>Practical lessons. Clearly labeled simulations. Safer everyday choices.</p></div></div>{active?<section className="lesson-body"><Button variant="ghost" onClick={()=>{setActive(null);setAnswer(null);setStatus('');}}><ArrowLeft/>All lessons</Button><h2 className="mt-5">{active.title}</h2><p>{active.body}</p><div className="content-band mt-6"><h3>{active.question}</h3><div className="quiz-options">{active.options.map((o,i)=><Button key={o} disabled={busy} variant={answer===i?'secondary':'outline'} onClick={()=>choose(i)}>{answer===i&&i===active.answer&&<CheckCircle2/>}{o}</Button>)}</div>{answer!==null&&<p className="status-note">{answer===active.answer?'Correct.':'Not quite.'} {active.explanation}</p>}{status&&<p className="status-note" role="status">{status}</p>}</div></section>:<><div className="control-row"><GraduationCap className="text-primary"/><span>{completed.length} of 6 lessons verified for this account</span></div><div className="lesson-grid">{lessons.map((l,i)=><article className="lesson-card" key={l.id}><span className="icon-tile tone-cyan">{completed.includes(l.id)?<CheckCircle2/>:<GraduationCap/>}</span><p className="eyebrow mt-4">LESSON {String(i+1).padStart(2,'0')} · 25 VIRTUAL COINS</p><h3>{l.title}</h3><p>{l.body.slice(0,115)}…</p><Button variant="outline" onClick={()=>{setActive(l);setAnswer(null);setStatus('');}}>Start lesson</Button></article>)}</div>{status&&<p role="status" className="status-note">{status}</p>}</>}</div>;}
export function RewardsPage(){const {user}=useSession();const [points,setPoints]=useState(0);const [count,setCount]=useState(0);const [error,setError]=useState('');useEffect(()=>{setPoints(0);setCount(0);if(user)supabase.from('lesson_rewards').select('points').then(({data,error})=>{if(error)setError('Rewards could not be loaded.');else{setCount(data?.length??0);setPoints((data??[]).reduce((s,r)=>s+r.points,0));}});},[user]);const level=count>=6?'Cyber Guardian':count>=4?'Phishing Expert':count>=2?'Cyber Defender':'Beginner Shield';return <div className="page"><div className="page-heading"><div><p className="eyebrow">CYBERSHIELD REWARDS</p><h1>Good habits deserve recognition.</h1><p>Virtual rewards for server-verified learning. No cash or real-world prizes.</p></div></div><div className="reward-level"><Trophy/><div><h2>{level}</h2><p>{points} CyberCoins · {count} verified lessons</p></div></div>{!user&&<div className="content-band"><h2>Keep your achievements</h2><p>Sign in to save verified lesson rewards. Repeating a lesson does not earn more points.</p><Button asChild className="mt-5"><Link to="/auth">Sign in</Link></Button></div>}<section className="content-band"><h2>Your next achievement</h2><p>Complete six safety lessons to reach Cyber Guardian. Each verified lesson awards 25 virtual CyberCoins once.</p><Button asChild className="mt-5"><Link to="/academy"><ShieldCheck/>Explore the academy</Link></Button></section><section className="content-band"><h2>Private by design</h2><p>Your points are private. A public leaderboard, daily streaks, avatar store and cosmetic purchases are not enabled yet.</p></section>{error&&<p className="form-error" role="alert">{error}</p>}</div>;}
