import { useState, useRef, useEffect } from 'react';
import { Link } from '@tanstack/react-router';
import { useServerFn } from '@tanstack/react-start';
import { Link2, MessageSquareText, ScanLine, QrCode, ShoppingBag, ArrowRight, ShieldCheck, LockKeyhole, Loader2, Upload, Camera, X, ClipboardPaste } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { analyzeMessage, urlSchema, validateImage, type Report } from '@/lib/cyber/analysis';
import { scanUrl } from '@/lib/cyber/scan.functions';
import { Result } from './report';
import { useSession } from './session';
export type Mode='url'|'message'|'screenshot'|'qr'|'shopping';
const tabs=[['url','URL scan','/scanner',Link2],['message','Message','/messages',MessageSquareText],['screenshot','Screenshot','/screenshots',ScanLine],['qr','QR code','/qr',QrCode],['shopping','Shopping','/shopping',ShoppingBag]] as const;
export function Scanner({mode='url',compact=false}:{mode?:Mode;compact?:boolean}) {
 const [text,setText]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const [result,setResult]=useState<Report|null>(null);const [consent,setConsent]=useState(false);const [save,setSave]=useState(false);const [preview,setPreview]=useState('');const [decoded,setDecoded]=useState('');const [camera,setCamera]=useState(false);const video=useRef<HTMLVideoElement>(null);const stream=useRef<MediaStream|null>(null);const {user}=useSession();const runScan=useServerFn(scanUrl);
 useEffect(()=>{if(mode==='url'){const params=new URLSearchParams(window.location.search);const shared=params.get('url')||params.get('text');if(shared&&shared.length<=2048)setText(shared);}return()=>{stream.current?.getTracks().forEach(t=>t.stop());};},[mode]);
 useEffect(()=>()=>{if(preview)URL.revokeObjectURL(preview);},[preview]);
 async function scan(value=text,asUrl=mode==='url'||mode==='shopping'){setError('');setBusy(true);setResult(null);try{const r=asUrl?await runScan({data:{url:urlSchema.parse(value),shopping:mode==='shopping',reputationConsent:consent,save:save&&Boolean(user)}}):analyzeMessage(value);setResult(r);}catch(e){setError(e instanceof Error?e.message:'Unable to complete this scan. Please retry.');}finally{setBusy(false);}}
 async function decodeImage(source:CanvasImageSource,w:number,h:number){const canvas=document.createElement('canvas');const scale=Math.min(1,2048/Math.max(w,h));canvas.width=Math.round(w*scale);canvas.height=Math.round(h*scale);const ctx=canvas.getContext('2d');if(!ctx)throw Error('Image processing is unsupported.');ctx.drawImage(source,0,0,canvas.width,canvas.height);const jsQR=(await import('jsqr')).default;const pixels=ctx.getImageData(0,0,canvas.width,canvas.height);const code=jsQR(pixels.data,pixels.width,pixels.height);if(!code)throw Error('No readable QR code found. Try a sharper, well-lit image.');setDecoded(code.data);setText(code.data);}
 async function upload(file:File|undefined){if(!file)return;setError('');setResult(null);try{validateImage(file);setPreview(URL.createObjectURL(file));setBusy(true);if(mode==='qr'){const image=await createImageBitmap(file);try{await decodeImage(image,image.width,image.height);}finally{image.close();}}else{const {createWorker}=await import('tesseract.js');const worker=await createWorker('eng');try{const {data}=await worker.recognize(file);if(!data.text.trim())throw Error('No readable text found. Try a clearer image or type the text.');setText(data.text.slice(0,12000));}finally{await worker.terminate();}}}catch(e){setError(e instanceof Error?e.message:'Image processing failed. Please retry or type manually.');}finally{setBusy(false);}}
 async function openCamera(){setError('');try{stream.current=await navigator.mediaDevices.getUserMedia({video:{facingMode:'environment'},audio:false});setCamera(true);setTimeout(()=>{if(video.current){video.current.srcObject=stream.current;void video.current.play();}},100);}catch{setError('Camera unavailable or permission denied. Upload a QR image instead.');}}
 function stopCamera(){stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;setCamera(false);}
 return <section className={`scanner-panel ${compact?'scanner-compact':''}`}><div className="scanner-top"><div><span className="eyebrow"><ShieldCheck size={14}/> INTELLIGENT THREAT CHECK</span><h2>{mode==='shopping'?'Check before you checkout.':mode==='message'?'Not sure about that message?':mode==='screenshot'?'See beyond the screenshot.':mode==='qr'?'Know where that QR leads.':'A safer click starts here.'}</h2></div><span className="private-label"><LockKeyhole size={13}/> Private by default</span></div><div className="scan-tabs" role="navigation" aria-label="Scanner type">{tabs.map(([id,label,to,Icon])=><Button key={id} variant="ghost" asChild className={mode===id?'scan-tab active':'scan-tab'}><Link to={to}><Icon/>{label}</Link></Button>)}</div><div className="scanner-body">{(mode==='screenshot'||mode==='qr')&&<><label className="upload-zone"><Upload/><span>Choose a {mode==='qr'?'QR code':'screenshot'} image</span><small>PNG, JPEG or WebP · Up to 8 MB · Processed on your device</small><input type="file" accept="image/png,image/jpeg,image/webp" aria-label="Upload image" disabled={busy} onChange={e=>upload(e.target.files?.[0])}/></label>{preview&&<img className="upload-preview" src={preview} alt="Uploaded image preview"/>}{mode==='screenshot'&&<p className="field-help">English OCR. Language files are downloaded; your image stays on this device.</p>}{mode==='qr'&&<Button variant="outline" onClick={openCamera} disabled={camera}><Camera/>Use camera</Button>}{camera&&<div className="camera-panel"><video ref={video} playsInline muted/><Button onClick={async()=>{if(video.current)try{await decodeImage(video.current,video.current.videoWidth,video.current.videoHeight);stopCamera();}catch(e){setError(e instanceof Error?e.message:'Unable to decode.');}}}>Decode current frame</Button><Button variant="ghost" onClick={stopCamera}><X/>Close camera</Button></div>}</>}
 <form onSubmit={e=>{e.preventDefault();void scan();}}><label className="field-label" htmlFor={`scan-${mode}`}>{mode==='url'||mode==='shopping'?'Website URL':mode==='qr'?'Decoded content':mode==='screenshot'?'Extracted text · editable':'Suspicious message'}</label>{mode==='url'||mode==='shopping'?<div className="url-field"><Link2 size={20}/><input id={`scan-${mode}`} value={text} onChange={e=>setText(e.target.value)} maxLength={2048} placeholder="Paste a link you want to check…" autoComplete="off"/><Button variant="ghost" size="icon" type="button" aria-label="Paste from clipboard" title="Paste from clipboard" onClick={async()=>{try{setText((await navigator.clipboard.readText()).slice(0,2048));}catch{setError('Clipboard unavailable. Paste the link manually.');}}}><ClipboardPaste/></Button><Button type="submit" size="lg" disabled={busy}>{busy?<Loader2 className="animate-spin"/>:<ShieldCheck/>}{busy?'Checking…':'Scan URL'}<ArrowRight/></Button></div>:<><textarea id={`scan-${mode}`} value={text} onChange={e=>setText(e.target.value)} maxLength={12000} rows={5} placeholder="Paste or edit the content to inspect…"/>{mode!=='qr'&&<Button type="submit" disabled={busy}>{busy?<Loader2 className="animate-spin"/>:<ShieldCheck/>}Analyze message<ArrowRight/></Button>}</>}
 {(mode==='url'||mode==='shopping'||mode==='qr')&&<div className="consent-row"><label><input type="checkbox" checked={consent} onChange={e=>setConsent(e.target.checked)}/> Allow sending this URL to Google for a reputation lookup, if configured.</label>{user&&mode!=='qr'&&<label><input type="checkbox" checked={save} onChange={e=>setSave(e.target.checked)}/> Save to my private history</label>}</div>}
 {mode==='qr'&&decoded&&<><p className="field-help">Decoded only. Nothing has been opened or paid.</p><Button type="button" disabled={busy||!urlSchema.safeParse(text).success} onClick={()=>scan(text,true)}><ShieldCheck/>Scan decoded URL</Button></>}
 </form>{error&&<p className="form-error" role="alert">{error}</p>}<div className="scan-footnote"><ShieldCheck size={14}/><span>Links are inspected, never opened. Heuristic warnings are not confirmed threats.</span></div></div>{result&&<Result report={result}/>}</section>;
}
